Added joint position telemetry to robot
huskyroboticsteam/Resurgence pull request #209
Opened 2023-02-11 20:53 UTC by DrDab

2023-02-12 00:53 UTC, abhaybd requested changes
Mostly pretty good! Just some minor changes needed.

2023-02-12 00:53 UTC, abhaybd commented on src/network/MissionControlProtocol.cpp
> +			 cur != robot::types::name_to_jointid.end(); cur++) {
Can you replace this with:
```c++
for (const auto& cur : robot::types::name_to_jointid) {
    ...
}
```

Which is shorter and cleaner

2023-02-12 00:53 UTC, abhaybd commented on src/network/MissionControlProtocol.cpp
> +				std::string str(frozenStr.data(), frozenStr.size());
Can these names be more descriptive? Maybe `jointNameFrozenStr` and `jointNameStr`?

2023-02-13 01:55 UTC, DrDab commented
Done!

2023-02-13 01:56 UTC, abhaybd approved these changes
Looks good!

2023-02-13 01:57 UTC, merged