Add heartbeat to Mission Control Protocol
huskyroboticsteam/Resurgence pull request #261
Opened 2023-08-23 04:33 UTC by abhaybd

This is a cleaned up version of functionality hacked together during CIRC 2023.

If the MC <-> Rover connection is severed (e.g. the cable disconnects) the disconnect handler isn't called, so the rover keeps running. This is unsafe behavior, since it might result in a runaway rover. We fix this by implementing a heartbeat in the websocket protocol. If enabled, then the rover will periodically ping MC and use pongs to feed a watchdog. If the watchdog starves, then the rover is E-stopped.

Note that this needs to be tested on the rover prior to being merged.

2023-09-21 17:45 UTC, huttongrabiel approved these changes
Here's the first review on this. I got sidetracked after doing this so I'll full review it again after this one.

2023-09-29 02:02 UTC, abhaybd commented on src/network/websocket/WebSocketServer.cpp
> +					auto& pd = this->protocolMap.at(path);
Per discussion in discord, we'll leave this as is to avoid messing with c++ weirdness, which we're not 100% sure if it exists here or not.

2023-09-29 02:02 UTC, abhaybd commented on src/network/websocket/WebSocketProtocol.h
> +		heartbeatInfo;
Agreed, we should probably standardize. I'm partial to the `_` suffix, but we can discuss and decide on something later.

2023-10-03 02:18 UTC, huttongrabiel requested changes

2023-10-03 02:18 UTC, huttongrabiel commented on src/network/websocket/WebSocketServer.cpp
> +	assert(protocolMap.find(payload) != protocolMap.end());
Don't blow up here. Use an if

2023-10-03 02:23 UTC, huttongrabiel requested changes

2023-10-03 02:23 UTC, huttongrabiel commented on src/network/websocket/WebSocketProtocol.h
> +	 * @param timeout The heartbeat timeout.
Better to write something along the lines of the "The time in milliseconds after which the heartbeat times out"

2023-10-10 01:19 UTC, huttongrabiel approved these changes

2023-10-10 01:49 UTC, merged