Full-Resolution Camera Downloads
huskyroboticsteam/Resurgence pull request #331
Opened 2024-07-18 06:13 UTC by Geeoon

Currently, clicking the download button will just download the client-side H264 compressed stream, which is fairly low quality.  This PR adds the ability to request full-resolution jpg images from the rover, and if the camera is available, a base64 encoded image will be sent to mission control at a much higher resolution than the normal client-side video stream.

2024-07-18 08:09 UTC, abhaybd commented on src/network/MissionControlTasks.cpp
> +			}
If the `camDP` datapoint is empty, this will respond with an empty string. Instead, we should probably not send a response at all.

2024-07-18 08:10 UTC, abhaybd commented on src/network/MissionControlTasks.cpp
> +void CameraStreamTask::sendCurrentFrame(const robot::types::CameraID& cam) {
Why do we need this method? Why can't the callback handler just call `robot::readCamera()`? We don't necessarily need to check `_open_streams` to see if the given stream has been opened or not, we can just read the frame from the camera.

2024-07-20 05:39 UTC, abhaybd commented
This looks great, will merge once the corresponding MC pr has been tested and merged.

2024-08-15 02:00 UTC, abhaybd commented
Didn't get to this during CIRC, Hutton can handle review and merging.

2024-11-19 02:38 UTC, huttongrabiel requested changes
ignore this just a demo

2024-11-19 02:38 UTC, huttongrabiel commented on src/network/MissionControlMessages.h
> +constexpr const char* CAMERA_FRAME_REQ_TYPE = "cameraFrameRequest";
Lets try to make these `frozen::string`

2025-02-08 19:33 UTC, huttongrabiel approved these changes

2025-04-26 19:13 UTC, imisaacwu approved these changes
looks great!

2025-04-26 19:14 UTC, merged